//***********************************************************************************************************
//**********************Analyze Consumers E-commerce Website Purchasing Behaviour****************************

//  Let's look at random sequence with a purchase event 

Behaviour
| where event_type == " purchase" 
| summarize Price=round(sum(price), 2) by category_code 
| extend category_code=replace_string(category_code, '.', ' ') 
| top 10 by Price desc  | render columnchart  


